### ISSUE TITLE
Use EBM on Longitudinal Data

### ISSUE THREAD

**Issue by JackieUW** [ucl-pond/kde_ebm#13]
Hi, I note that in your examples, the EBM is fitted on cross-sectional demo data.

However, I hope to fit EBM on longitudinal data (as what you did on the family AD cohort in the NeuroImage 2012 paper).

How should I estimate <img src="https://render.githubusercontent.com/render/math?math=p(x_{ij}|E_i)"> and <img src="https://render.githubusercontent.com/render/math?math=p(x_{ij}|~E_i)"> in longitudinal data? Could you provide some pipeline instructions?

Thx.

**Comment by noxtoby** [comment]
If you read the NeuroImage 2012 paper closely, you’ll see that the longitudinal values (brain volumes) were converted to cross-sectional values of change (atrophy), then the EBM was fit.

In general, multiple time points per individual are not independent and so including longitudinal data would violate one of the assumptions of the EBM.

You could:
- use a model that is designed for longitudinal data (maybe a hidden Markov model);
- derive a new EBM that relaxes the assumption of independence;
- throw caution to the wind and chuck all the longitudinal data into the EBM;
- convert the longitudinal data into cross-sectional change, *a la* Fonteijn-NeuroImage-2012;
- fit (train) the EBM on baseline data (first time point), then test the trained model by staging the followup data.

Good luck
