### ISSUE TITLE
Enquires Regarding Baseline Factors

### ISSUE THREAD

**Issue by sardnar** [ucl-pond/kde_ebm#17]
Hello,

Thank you for putting this tool. I have similar problem to the one described in the demo, but my cross-sectional data is quite heterogenous. i.e I have wide range of disease history, age ... etc. 

So, my question is if there is a way to (statistically) standardize for these patient factors instead of stratification as I will lose alot of power and will be difficult to interpret if I stratified. 

Best Regards.

**Comment by noxtoby** [comment]
I'm closing this because it's a general statistical query, not an EBM issue.

FWIW, there are lots of ways to "adjust" / "correct" for confounding factors in disease progression models. For example, some are mentioned in [arXiv:2211.05786](https://arxiv.org/abs/2211.05786).

**Comment by noxtoby** [comment]
That is probably what I would do, but a GitHub issue on this repository is not the place to discuss general statistical methodology.
