### ISSUE TITLE
utils.py bug

### ISSUE THREAD

**Issue by LeonAksman** [ucl-pond/kde_ebm#4]
Hey Neil,

I've run into a bug with pySuStaIn when it calls kde_ebm's fit_all_kde_models with only the first two arguments passed in (X and y). In theory, the function should work this way, because the other two arguments (implement_fixed_controls, patholog_dirn_array) are assigned default values of None. 

Unfortunately when you run it this way though, the code breaks on this line:

patholog_dirn = patholog_dirn_array[i]

because it's indexing into None. So an easy change would be:

patholog_dirn = patholog_dirn_array[i] if patholog_dirn_array is not None else None

which just checks that it's not None. 

Best,
Leon

**Comment by noxtoby** [comment]
Cheers Leon. Fixed with [this commit](https://github.com/ucl-pond/kde_ebm/commit/2a4f469dec95745482018903b2998fd07fce82e1).
